<?php

namespace App\DTOs;

class
PaymentResponseDto
{
    public function __construct(
        public int $gatewayId,
        public string $dateCreated,
        public ?string $dateApproved,
        public string $dateLastUpdated,
        public ?string $dateExpiration,
        public ?string $moneyReleaseDate,
        public string $moneyReleaseStatus,
        public string $operationType,
        public string $issuerId,
        public string $paymentMethodId,
        public string $paymentTypeId,
        public string $status,
        public string $statusDetail,
        public string $currencyId,
        public ?string $description,
        public bool $liveMode,
        public ?int $authorizationCode,
        public ?string $moneyReleaseSchema,
        public float $taxesAmount,
        public ?string $counterCurrency,
        public string $collectorId,
        public ?string $externalReference,
        public float $transactionAmount,
        public float $transactionAmountRefunded,
        public ?string $paymentMethodReferenceId,
        public float $netReceivedAmount,
        public float $totalPaidAmount,
        public ?string $feeType,
        public ?float $feeAmount,
        public ?string $statementDescriptor,
        public ?string $externalResourceUrl,
        public ?string $qrCodeBase64,
        public ?string $qrCode,
        public ?string $ticketUrl,
    ){}

    public static function fromMercadoPago(array $data): self
    {
        return new self(
            gatewayId: $data['id'],
            dateCreated: $data['date_created'],
            dateApproved: $data['date_approved'],
            dateLastUpdated: $data['date_last_updated'],
            dateExpiration: $data['date_of_expiration'],
            moneyReleaseDate: $data['money_release_date'],
            moneyReleaseStatus: $data['money_release_status'],
            operationType: $data['operation_type'],
            issuerId: $data['issuer_id'],
            paymentMethodId: $data['payment_method_id'],
            paymentTypeId: $data['payment_type_id'],
            status: $data['status'],
            statusDetail: $data['status_detail'],
            currencyId: $data['currency_id'],
            description: $data['description'],
            liveMode: $data['live_mode'],
            authorizationCode: $data['authorization_code'],
            moneyReleaseSchema: $data['money_release_schema'],
            taxesAmount: $data['taxes_amount'],
            counterCurrency: $data['counter_currency'],
            collectorId: $data['collector_id'],
            externalReference: $data['external_reference'],
            transactionAmount: $data['transaction_amount'],
            transactionAmountRefunded: $data['transaction_amount_refunded'],
            paymentMethodReferenceId: data_get($data, 'transaction_details.payment_method_reference_id'),
            netReceivedAmount: data_get($data, 'transaction_details.net_received_amount'),
            totalPaidAmount: data_get($data, 'transaction_details.total_paid_amount'),
            feeType: data_get($data, 'transaction_details.fee_type'),
            feeAmount: data_get($data, 'transaction_details.fee_amount', 0),
            statementDescriptor: $data['statement_descriptor'],
            externalResourceUrl: data_get($data, 'transaction_details.external_resource_url'),
            qrCodeBase64: data_get($data, 'point_of_interaction.transaction_data.qr_code_base64'),
            qrCode: data_get($data, 'point_of_interaction.transaction_data.qr_code'),
            ticketUrl: data_get($data, 'point_of_interaction.transaction_data.ticket_url'),
        );
    }

    public function toArray(): array
    {
        return [
            'gateway_id' => $this->gatewayId,
            'date_created' => $this->dateCreated,
            'date_approved' => $this->dateApproved,
            'date_last_updated' => $this->dateLastUpdated,
            'date_expiration' => $this->dateExpiration,
            'money_release_date' => $this->moneyReleaseDate,
            'money_release_status' => $this->moneyReleaseStatus,
            'operation_type' => $this->operationType,
            'issuer_id' => $this->issuerId,
            'payment_method_id' => $this->paymentMethodId,
            'payment_type_id' => $this->paymentTypeId,
            'status' => $this->status,
            'status_detail' => $this->statusDetail,
            'currency_id' => $this->currencyId,
            'description' => $this->description,
            'live_mode' => $this->liveMode,
            'authorization_code' => $this->authorizationCode,
            'money_release_schema' => $this->moneyReleaseSchema,
            'taxes_amount' => $this->taxesAmount,
            'counter_currency' => $this->counterCurrency,
            'collector_id' => $this->collectorId,
            'external_reference' => $this->externalReference,
            'transaction_amount' => $this->transactionAmount,
            'transaction_amount_refunded' => $this->transactionAmountRefunded,
            'payment_method_reference_id' => $this->paymentMethodReferenceId,
            'net_received_amount' => $this->netReceivedAmount,
            'total_paid_amount' => $this->totalPaidAmount,
            'fee_type' => $this->feeType,
            'fee_amount' => $this->feeAmount,
            'external_resource_url' => $this->externalResourceUrl,
            'qr_code_base64' => $this->qrCodeBase64,
            'qr_code' => $this->qrCode,
            'ticket_url' => $this->ticketUrl,
            'statement_descriptor' => $this->statementDescriptor,
        ];
    }

}
